// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconCarbon:vehicleServices': typeof import('~icons/carbon/vehicle-services')['default']
    'IconCib:instagram': typeof import('~icons/cib/instagram')['default']
    'IconIconParkOutline:messageFailed': typeof import('~icons/icon-park-outline/message-failed')['default']
    'IconIconParkOutline:messageSuccess': typeof import('~icons/icon-park-outline/message-success')['default']
    'IconIon:clock': typeof import('~icons/ion/clock')['default']
    'IconIon:closeRound': typeof import('~icons/ion/close-round')['default']
    'IconLogos:facebook': typeof import('~icons/logos/facebook')['default']
    'IconLogos:googleIcon': typeof import('~icons/logos/google-icon')['default']
    'IconMdi:arrowLeft': typeof import('~icons/mdi/arrow-left')['default']
    'IconMdi:carClock': typeof import('~icons/mdi/car-clock')['default']
    'IconMdi:carCog': typeof import('~icons/mdi/car-cog')['default']
    'IconMdi:carInfo': typeof import('~icons/mdi/car-info')['default']
    'IconMdi:carTurbocharger': typeof import('~icons/mdi/car-turbocharger')['default']
    'IconMdi:cellphone': typeof import('~icons/mdi/cellphone')['default']
    'IconMdi:chevronDown': typeof import('~icons/mdi/chevron-down')['default']
    'IconMdi:emailFast': typeof import('~icons/mdi/email-fast')['default']
    'IconMdi:engineOffOutline': typeof import('~icons/mdi/engine-off-outline')['default']
    'IconMdi:information': typeof import('~icons/mdi/information')['default']
    'IconMdi:mapMarkerRadius': typeof import('~icons/mdi/map-marker-radius')['default']
    'IconMdi:menu': typeof import('~icons/mdi/menu')['default']
    'IconMdi:oilLevel': typeof import('~icons/mdi/oil-level')['default']
    'IconMdi:phoneForward': typeof import('~icons/mdi/phone-forward')['default']
    'IconRi:teamLine': typeof import('~icons/ri/team-line')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
