// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconCib:instagram': typeof import('~icons/cib/instagram')['default']
    'IconIconParkOutline:messageSuccess': typeof import('~icons/icon-park-outline/message-success')['default']
    'IconIon:clock': typeof import('~icons/ion/clock')['default']
    'IconIon:closeRound': typeof import('~icons/ion/close-round')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconLogos:facebook': typeof import('~icons/logos/facebook')['default']
    'IconLogos:googleIcon': typeof import('~icons/logos/google-icon')['default']
    'IconMdi:carClock': typeof import('~icons/mdi/car-clock')['default']
    'IconMdi:carInfo': typeof import('~icons/mdi/car-info')['default']
    'IconMdi:carTurbocharger': typeof import('~icons/mdi/car-turbocharger')['default']
    'IconMdi:emailFast': typeof import('~icons/mdi/email-fast')['default']
    'IconMdi:engineOffOutline': typeof import('~icons/mdi/engine-off-outline')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconMdi:mapMarkerRadius': typeof import('~icons/mdi/map-marker-radius')['default']
    'IconMdi:menu': typeof import('~icons/mdi/menu')['default']
    'IconMdi:oilLevel': typeof import('~icons/mdi/oil-level')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
