name = "dubsquared-next"
account_id = "e447e4c0da31cb819d3fead9bccbce1d"
workers_dev = true
compatibility_date = "2022-04-07"
node_compat = true
main = ".output/server/index.mjs"

[site]
bucket = ".output/public"

[build]
command = ""

[vars]
NUXT_PUBLIC_COMPANY_EMAIL = "info@dubsquared.com"
NUXT_PUBLIC_COMPANY_PHONE = "817-277-5593"