name = "dubsquared-next"
type = "javascript"
account_id = "e447e4c0da31cb819d3fead9bccbce1d"
workers_dev = true
compatibility_date = "2022-04-07"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = ""
upload.format = "service-worker"

[vars]
NUXT_PUBLIC_COMPANY_EMAIL = "info@dubsquared.com"
NUXT_PUBLIC_COMPANY_PHONE = "817-277-5593"